version: "3"
services:
  mysql-tecdoc:
    image: mysql:5.7
    command: >
      --max_allowed_packet=500000M
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-tecdoc:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=tecdoc
    container_name: mysql-tecdoc
  pg-tecdoc:
    image: postgres:11-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./pg-tecdoc:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$ROOT_PASSWORD
      - POSTGRES_PASSWORD=$ROOT_PASSWORD
    container_name: pg-tecdoc
